ISSUES-129: Increased to FileField(max_length=2000) from max_length=100 which was too short.
The MailAttachment.document field is too short & raises the error below. The default FileField(..., max_length=100) does not hold long enough filenames.
Can MailAttachment.document accept a configured max_length, or have the default set higher?

ERROR: [django.security.SuspiciousFileOperation: 204] Storage can not find an available filename Please make sure that the corresponding file field allows sufficient "max_length".